name: Node Example
on: [push]

jobs:
  print_info:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Print Name
      run: echo "Nombre Completo: Nathan Lokier Cohen"
    - name: Print Node Version
      run: node --version
    - name: Print Expediente
      run: echo "Expediente: 734292"
